In [16]:
import FederatedLearning
import tensorflow as tf
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense
import importlib
importlib.reload(FederatedLearning)
import asyncio

In [17]:
#While connection.status:
    #model = connection.model -> Check if server sends new model
    #gradients = model.fit(x, y) -> gradients:Dict{model:model_id, gradients:gradients}
    #connection.sendGradients(gradients) -> WebSocket send request

In [18]:
# Define the CNN model
model = tf.keras.models.Sequential()

# Convolutional and Max-Pooling Layers
model.add(Dense(10, activation='relu', input_shape=(1, 2)))
model.add(Dense(3, activation='softmax'))  # Example output layer with 10 classes

# Compile the model
model.compile(optimizer='adam',
              loss='categorical_crossentropy',  # Use appropriate loss function for your problem
              metrics=['accuracy'])

# Print a summary of the model architecture
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_4 (Dense)             (None, 1, 10)             30        
                                                                 
 dense_5 (Dense)             (None, 1, 3)              33        
                                                                 
Total params: 63 (252.00 Byte)
Trainable params: 63 (252.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [24]:
ip = "localhost" # Global or Local IP
port = "8765"

key ="aaa"
connection = FederatedLearning.Client(ip, key, port=port) # Connection object
#connection.status -> websocket connection status:Boolean

2
3
Sending message
Message: Connection made


In [25]:
asyncio.create_task(connection.set_admin())

<Task pending name='Task-26' coro=<Client.set_admin() running at C:\Users\USER\Documents\GitHub\Federated-Learning\FederatedLearning\client.py:55>>

2
3
Sending message
Message: Admin key overriden


In [27]:
asyncio.create_task(connection.send_model(model.to_json()))

<Task pending name='Task-28' coro=<Client.send_model() running at C:\Users\USER\Documents\GitHub\Federated-Learning\FederatedLearning\client.py:62>>

2
3
Sending message
Message: Model Distributed


In [32]:
asyncio.create_task(connection.send_weights(model.get_weights()))

<Task pending name='Task-32' coro=<Client.send_weights() running at C:\Users\USER\Documents\GitHub\Federated-Learning\FederatedLearning\client.py:80>>

1
2
2
3
Sending message
Message: Weights Distributed


In [28]:
model.get_weights()

[array([[-0.37771264,  0.32555586, -0.40472084, -0.1420443 , -0.04335189,
         -0.17475635, -0.60183287, -0.5905441 ,  0.03480417,  0.32485455],
        [-0.28305233, -0.14429295, -0.5389533 , -0.50852585, -0.51347136,
          0.09970427,  0.58541316,  0.21622515,  0.57514316,  0.30779225]],
       dtype=float32),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32),
 array([[-0.3987252 , -0.23799255, -0.37146914],
        [-0.4987868 , -0.10968137,  0.34543216],
        [ 0.62572336, -0.6648796 , -0.08511484],
        [ 0.6563411 , -0.3163089 , -0.27656496],
        [ 0.62777925, -0.65295047,  0.40987504],
        [-0.5441405 , -0.13821965, -0.18268847],
        [-0.13480943, -0.4318182 , -0.07422566],
        [ 0.4102205 , -0.40128797,  0.51833487],
        [ 0.2989769 ,  0.16769719, -0.45060468],
        [-0.3351485 , -0.59135693, -0.5054478 ]], dtype=float32),
 array([0., 0., 0.], dtype=float32)]