In [1]:
import FederatedLearning
import tensorflow as tf
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense
import importlib
importlib.reload(FederatedLearning)
import asyncio

C:\Users\USER\anaconda3\lib\site-packages\scipy\__init__.py:138: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.24.3)
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion} is required for this version of "


In [2]:
ip = "localhost" # Global or Local IP
port = "8765"
key = "bbb"

In [9]:
connection = FederatedLearning.Client(ip, key, port=port)

2
3
Sending message
Message: Connection made


In [19]:
asyncio.create_task(connection.receive_message())

<Task pending name='Task-21' coro=<Client.receive_message() running at C:\Users\USER\Documents\GitHub\Federated-Learning\FederatedLearning\client.py:45>>

Test
set_weights


In [16]:
model = connection.get_model()
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_4 (Dense)             (None, 1, 10)             30        
                                                                 
 dense_5 (Dense)             (None, 1, 3)              33        
                                                                 
Total params: 63 (252.00 Byte)
Trainable params: 63 (252.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [17]:
model.get_weights()

[array([[-0.37771264,  0.32555586, -0.40472084, -0.1420443 , -0.04335189,
         -0.17475635, -0.60183287, -0.5905441 ,  0.03480417,  0.32485455],
        [-0.28305233, -0.14429295, -0.5389533 , -0.50852585, -0.51347136,
          0.09970427,  0.58541316,  0.21622515,  0.57514316,  0.30779225]],
       dtype=float32),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32),
 array([[-0.3987252 , -0.23799255, -0.37146914],
        [-0.4987868 , -0.10968137,  0.34543216],
        [ 0.62572336, -0.6648796 , -0.08511484],
        [ 0.6563411 , -0.3163089 , -0.27656496],
        [ 0.62777925, -0.65295047,  0.40987504],
        [-0.5441405 , -0.13821965, -0.18268847],
        [-0.13480943, -0.4318182 , -0.07422566],
        [ 0.4102205 , -0.40128797,  0.51833487],
        [ 0.2989769 ,  0.16769719, -0.45060468],
        [-0.3351485 , -0.59135693, -0.5054478 ]], dtype=float32),
 array([0., 0., 0.], dtype=float32)]

set_weights


In [12]:
import numpy as np
from ast import literal_eval

In [17]:
def convert_numpy_arrays_to_lists(data):
        if isinstance(data, np.ndarray):
            return data.tolist()
        elif isinstance(data, list):
            return [convert_numpy_arrays_to_lists(item) for item in data]
        else:
            return data  # For other data types, just return as is'
        

In [33]:
weight_str = convert_numpy_arrays_to_lists(model.get_weights())
weight_str = str(weight_str)

In [35]:
try:
    weight_p = literal_eval(weight_str)
    print("Parsed Data:", weight_p)
except Exception as e:
    print("Parsing Error:", e)

Parsed Data: [[[0.49118679761886597, 0.6883921027183533, 0.07727015018463135, -0.2246851921081543, -0.13214421272277832, -0.07256138324737549, 0.19693297147750854, 0.7069842219352722, 0.5267763733863831, -0.41136234998703003], [0.6341050267219543, 0.29055750370025635, 0.17937195301055908, 0.4077391028404236, 0.6691189408302307, 0.7043063044548035, 0.6586353182792664, -0.131860613822937, -0.5932291746139526, 0.0072138309478759766]], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [[-0.64896559715271, -0.27103322744369507, -0.40202510356903076], [0.033091187477111816, -0.041729092597961426, 0.04798156023025513], [0.5189518928527832, 0.4021279811859131, 0.3221513032913208], [0.6272619962692261, -0.6645746231079102, -0.568984866142273], [-0.09792709350585938, -0.34337061643600464, -0.061401426792144775], [-0.5306340456008911, 0.4867899417877197, -0.6355820298194885], [0.4187157154083252, 0.24121731519699097, -0.24626165628433228], [-0.5431725978851318, 0.2252829670906067, -0.0373710393